/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/demo` | `/demo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/development/create` | `/development/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/unit/create` | `/unit/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/unit/type-models` | `/unit/type-models`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/camera/[id]` | `/camera/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/development/[id]` | `/development/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/unit/[id]` | `/unit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/demo` | `/demo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/development/create` | `/development/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/unit/create` | `/unit/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/unit/type-models` | `/unit/type-models`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/camera/[id]` | `/camera/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/development/[id]` | `/development/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/unit/[id]` | `/unit/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/demo${`?${string}` | `#${string}` | ''}` | `/demo${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/development/create${`?${string}` | `#${string}` | ''}` | `/development/create${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/unit/create${`?${string}` | `#${string}` | ''}` | `/unit/create${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/unit/type-models${`?${string}` | `#${string}` | ''}` | `/unit/type-models${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/demo` | `/demo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/development/create` | `/development/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/unit/create` | `/unit/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/unit/type-models` | `/unit/type-models`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | `${'/(app)'}/camera/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/camera/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/development/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/development/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/unit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/unit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/camera/[id]` | `/camera/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/development/[id]` | `/development/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/unit/[id]` | `/unit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
